### ISSUE TITLE
The named parameter 'label' isn't defined.

### ISSUE THREAD

**Issue by amanijoseph87** [SongTube/SongTube-App#13]
I get this error on navigationBar.dart 

https://github.com/SongTube/SongTube-App/blob/422ad53ea27531e1c83e7dbc828daeeaa72f3ffe/lib/ui/components/navigationBar.dart#L45

`BottomNavigationBarItem(
            icon: Icon(EvaIcons.homeOutline),
            label: Languages.of(context).labelHome
          ),
          BottomNavigationBarItem(
            icon: Icon(EvaIcons.cloudDownloadOutline),
            label: Languages.of(context).labelDownloads
          ),
          BottomNavigationBarItem(
            icon: Icon(EvaIcons.musicOutline),
            label: Languages.of(context).labelMedia
          ),
          BottomNavigationBarItem(
            icon: Icon(EvaIcons.videoOutline),
            label: "YouTube"
          ),
          BottomNavigationBarItem(
            icon: Icon(MdiIcons.dotsHorizontal),
            label: Languages.of(context).labelMore
          )
        ]`

**Comment by Artx-II** [comment]
For the BottomNavigationBarItem, the property "text" was deprecated in the lastest Flutter update in favor or "label" which has better text scaling, you seem to have this issue because in the commit 08356e7 I replaced "text" with "label" and it looks like your Flutter SDK is outdated, that would explain why it gives you that error.

Try updating your Flutter SDK and report back if it works to close this issue 👍

**Comment by amanijoseph87** [comment]
Thanks, this work perfectly after upgrade.
