### ISSUE TITLE
Cannot write to SD card after opening SongTube

### ISSUE THREAD

**Issue by san-ha-kim** [SongTube/SongTube-App#198]
### Steps to reproduce

1. Run the app
2. Grant permissions
3. App crashes
4. Now I can't take photos to save to my SD card

### Expected behavior

My camera app, and other apps, should be able to write to SD card.

### Actual behavior

Camera cannot save photos to SD card
I tried formatting the card, but it still doesn't work.
I've also put the card in my DSLR, and the card doesn't work there as well.

### SongTube version

6.4.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by enweazudaniel** [comment]
There could be several reasons why your camera is unable to save photos to your SD card. Here are a few things you can try to troubleshoot the issue:

Check the SD card for any physical damage, such as cracks or bends. If the card is damaged, it may not be functioning properly and you may need to replace it.

Make sure the SD card is properly inserted into the camera. It should be fully seated in the card slot, with the label facing the correct direction.

Check the camera's settings to ensure that it is set to save photos to the SD card, rather than to the camera's internal memory.

Try formatting the SD card within the camera. This will erase all of the data on the card, so make sure you have backed up any important files before doing this.

If the camera is still unable to save photos to the SD card after trying these steps, it is possible that the card is faulty or that there is a problem with the camera itself. In this case, you may need to try a different SD card or contact the manufacturer for assistance.

**Comment by Artx-II** [comment]
This shouldn't happen with the new SongTube. If the case persists, then feel free to open this issue again.
