### ISSUE TITLE
Linux & Windows app

### ISSUE THREAD

**Issue by xmha97** [SongTube/SongTube-App#206]
### Describe your suggested feature

Flutter is a cross-platform framework.
Please release Linux and Windows version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
This is not possible since some of the libraries this project uses are Android only. One of them provides the app's core functionality, which is NewPipe Extractor, and it's only available for Android.

In the future a solution for this can be developed and I can build the app for other platforms, but currently it's way too much work.

**Comment by xmha97** [comment]
Ok, thanks for your reply.
