### ISSUE TITLE
[Feature Request] Add InAppUpdate. 

### ISSUE THREAD

**Issue by Clashkid155** [SongTube/SongTube-App#22]
Your current implementation of in app update redirects the user to  your Telegram channel. I'm suggesting a different  method.

I already did some work on this concept but unfortunately, i wasn't able to recreate Play Store like update but i did create something.

[Video 😩](https://streamable.com/zq8fwz)
What do you think ?
Audio might be a little bit loud.

It download's according to you phone architecture (Abi), my logic probably isn't fool proof but i know it works (on my device 😢) 

**Additional plugin** 
- [install_plugin](https://pub.dev/packages/install_plugin)

**Comment by Artx-II** [comment]
I thought about that and your implementation from the video I saw looks great, the issue is that we need to sort out for which architecture the apk was built for, almost everyone installs the fat apk (for arm & arm64), others install the arm only or arm64 only. 

Your CPU might be arm64, but you might have the fat apk or the arm only apk installed and trying to install the arm64 apk will fail. That is where I got stuck and so just decided to redirects the user to the telegram channel.

**Comment by Clashkid155** [comment]
I think i get what you mean now, arm app won't install over  arm64 app, but if your architecture is arm64 then it will install. What I'm saying is if your device is arm64 and you installed the arm or general apk previously whenever a new update is released my tweak tries to determine your device arch so even if you have the general  or arm apk of songtube installed and your device is arm64 if will get and install it over them since your device is arm64.

From my test on an arm64 device:

Arm64 installs over any apk (arm or general).

Arm can install over general but can't install over arm64 apk.

Arm64 and arm apk can install over general apk.

General can't install over arm or arm64 apk.

Will see if i can test on an arm device.

**Comment by Clashkid155** [comment]
Whenever it's ready

**Comment by Artx-II** [comment]
I really like your implementation on this, now that I simplified new releases to a single APK I believe it is now a lot easier 😃

**Comment by Clashkid155** [comment]
Will rewrite/update the code and pr

**Comment by Artx-II** [comment]
Implemented with commit #8e3990e, thanks!
