### ISSUE TITLE
[Enhancement] Few enhancements.

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#39]
Few enhancements.

1. Media listing is limited to phone memory. It doesn't check for external card.
2. While updating tags on media list the more option button is very precise on click. Suppose I clicked more option without playing media the `ListTile` tap always overrides, trailing icon tap. The same happens when playing media as well. WHatever is playing it always start with media which I tap for editting tag.
3. I didn't see option to remove cover. If I updated tag and updated any cover by mistake, It wont let me clear the cover without cancelling page. Scenario also exist for media which already persist albumcover.
4. Many other sites are available like soundcloud, vimeo. Can we integrate downloading to that sites as well or we are limited to Youtube.
5. Media Manager can we have option to segregate based on Artist, Artist-albums, Albums, Genre along with Song list option(default which exist)

**Comment by bohrasankalp** [comment]
6. Few Audio format are not supporting editting metadata. This I realized when I click save button. So instead of checking at failure Can't it be checked and validated before rending metadata edit page. Or Either on metadata page that particular file format is not supported.
7. Audio/Video player should have some circular span area which moves with progress while playing.

**Comment by Artx-II** [comment]
It seems that download from other sites would over-complicate things, since I'm still implementing and bringing more core features to the app (as well as trying to improve my ugly code), that idea will be left aside for quite some time.

Now that we're missing is just one feature from your request (Music ordering by album, artist, etc...) I will close this issue and open a new one.
